name: CI/CD for Fullstack App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies for backend
      working-directory: Chacobache_API
      run: npm install

    - name: Run backend tests
      working-directory: Chacobache_API
      run: npm test

    - name: Setup Chromium
      uses: browser-actions/setup-chromium@v1

    - name: Install dependencies for frontend
      working-directory: Chacobache
      run: npm install

    - name: Run frontend tests
      working-directory: Chacobache
      run: npm test

    - name: Build and Deploy Frontend
      working-directory: Chacobache
      run: npm run build
